name: Newman Run

on: [push, pull_request]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - name: install 
           run: npm install -g newman-reporter-htmlextra
         - name: Run_collection
           run: newman run Trello_Pavel.postman_collection.json -e Board.postman_environment.json --reporters cli,htmlextra --reporter-htmlextra-export result_html.html
         - name : fdvs
           run: ls 

  

