name: Newman Run

on: [push, pull_request]

jobs:
   build:

    runs-on: ubuntu-latest
  
  
    steps:
   

    - name: Run API Tests
      id: run-newman
      uses: anthonyvscode/newman-action@v1
      with:
        collection: collection.json
        reporters: cli
        run: newman run "Trello_Pavel.postman_collection.json"

  

