name: Newman Run

on: [push, pull_request]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - name : fdvs
           run: ls
         - name: install 
           run: npm install newman-reporter-html
         - name: Run_collection
           run: newman run Trello_Pavel.postman_collection.json -e Board.postman_environment.json --reporters cli,html
 

  

