name: Newman Run

on: 
   workflow_dispatch:
  

jobs:
   build:
      runs-on: ubuntu-latest
      
      steps:
         - name: checkout
           uses: actions/checkout@v3
         
         - name: install 
           run: npm install -g newman-reporter-htmlextra
         
         - name: Run_collection
           run: newman run Trello_Pavel.postman_collection.json -e Board.postman_environment.json --reporters cli,htmlextra --reporter-htmlextra-export testResults/result_html.html
         
         - name : ls
           run: ls 
           
         - name: publish test results
           uses: actions/upload-artifact@v3
           with:
              name: reports
              path: testResults/
